# Generated by Django 5.2.1 on 2025-07-14 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('electronics', 'Электроника'), ('furniture', 'Мебель'), ('clothing', 'Одежда'), ('books', 'Книги'), ('other', 'Другое')], max_length=100)),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/у')], max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принята'), ('declined', 'Отклонена')], default='pending', max_length=10)),
                ('ad_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to='ads.ad')),
                ('ad_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to='ads.ad')),
            ],
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['title'], name='ads_ad_title_ce8d95_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['city'], name='ads_ad_city_865388_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['category'], name='ads_ad_categor_aafbda_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['condition'], name='ads_ad_conditi_1d704d_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['user'], name='ads_ad_user_id_b85512_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangeproposal',
            index=models.Index(fields=['status'], name='ads_exchang_status_de2e30_idx'),
        ),
    ]
